// my-angular-app/src/app/components/word-details/word-details.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-word-details',
  template: `
    <div class="max-w-md mx-auto my-4 rounded-xl border bg-card text-card-foreground shadow">
      <div class="flex flex-col space-y-1.5 p-6">
        <div class="font-semibold leading-none tracking-tight">{{ word }}</div>
        <div class="text-sm text-muted-foreground">{{ pronunciation }}</div>
      </div>
      <div class="p-6 pt-0">
        <div class="mb-4">
          <h3 class="font-semibold">Usage:</h3>
          <p>{{ usage }}</p>
        </div>
        <div class="mb-4">
          <h3 class="font-semibold">Example:</h3>
          <p>{{ example }}</p>
        </div>
        <div>
          <h3 class="font-semibold">Origin:</h3>
          <p>{{ origin }}</p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .bg-card {
      background-color: var(--card);
    }
    .text-card-foreground {
      color: var(--card-foreground);
    }
    .text-muted-foreground {
      color: var(--muted-foreground);
    }
  `]
})
export class WordDetailsComponent {
  @Input() word: string = '';
  @Input() pronunciation: string = '';
  @Input() usage: string = '';
  @Input() example: string = '';
  @Input() origin: string = '';
}

// src/components/WordDetails.tsx
import React from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui';

interface WordDetailsProps {
  word: string;
  pronunciation: string;
  usage: string;
  example: string;
  origin: string;
}

const WordDetails: React.FC<WordDetailsProps> = ({ word, pronunciation, usage, example, origin }) => {
  return (
    <Card className="max-w-md mx-auto my-4">
      <CardHeader>
        <CardTitle>{word}</CardTitle>
        <CardDescription>{pronunciation}</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="mb-4">
          <h3 className="font-semibold">Usage:</h3>
          <p>{usage}</p>
        </div>
        <div className="mb-4">
          <h3 className="font-semibold">Example:</h3>
          <p>{example}</p>
        </div>
        <div>
          <h3 className="font-semibold">Origin:</h3>
          <p>{origin}</p>
        </div>
      </CardContent>
    </Card>
  );
};

export default WordDetails;
